# Generated by Django 4.2 on 2023-04-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('Schedule_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Source', models.CharField(max_length=20)),
                ('Destination', models.CharField(max_length=20)),
                ('Start_time', models.DateTimeField()),
                ('End_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('Track_no', models.IntegerField(primary_key=True, serialize=False)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('T_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('T_Name', models.CharField(max_length=20)),
                ('T_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('S_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('S_Name', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=30)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.tracks')),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('P_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('P_Name', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=1)),
                ('Age', models.IntegerField()),
                ('Seat_number', models.IntegerField()),
                ('Coaches', models.CharField(max_length=2)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.train')),
            ],
        ),
        migrations.CreateModel(
            name='Moves_on',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.tracks', unique=True)),
                ('Train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.train', unique=True)),
            ],
            options={
                'unique_together': {('Track', 'Train')},
            },
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.schedule', unique=True)),
                ('Train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.train', unique=True)),
            ],
            options={
                'unique_together': {('Schedule', 'Train')},
            },
        ),
    ]
