# Generated by Django 4.2 on 2023-04-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_moves_on_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves_on',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.train', unique=True),
        ),
    ]
