# Generated by Django 4.2 on 2023-04-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_follows_schedule_id_alter_follows_train'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.AlterUniqueTogether(
            name='follows',
            unique_together={('schedule', 'train')},
        ),
    ]
